-- Elimina conexiones spleep de la BD que tienen 60 minutos en ese modo

DECLARE @V_SPID INT
DECLARE C_USERS CURSOR
   FAST_FORWARD FOR
   SELECT SPID
   FROM MASTER..SYSPROCESSES (NOLOCK)
   WHERE SPID>50 
   AND STATUS='SLEEPING' 
   AND DATEDIFF(MI,LAST_BATCH,GETDATE())>=60
   AND SPID<>@@SPID

OPEN C_USERS
FETCH NEXT FROM C_USERS INTO @V_SPID
WHILE (@@FETCH_STATUS=0)
BEGIN
  PRINT 'KILLING '+CONVERT(VARCHAR,@V_SPID)+'...'
  EXEC('KILL '+@V_SPID)
  FETCH NEXT FROM C_USERS INTO @V_SPID
END

CLOSE C_USERS
DEALLOCATE C_USERS