-- NUMERO DE CONEXIONES EN BASE DE DATOS

USE [master]
GO

-- 1. MUESTRA NOMBRE DE BD, CANTIDAD DE CONEXIONES, LOGIN, HOSTNAME Y FECHA DE EJECUCION DE CONSULTA
SELECT 
    DB_NAME(DBID) AS DBNAME, 
    COUNT(DBID) AS NUMBEROFCONNECTIONS,
    LOGINAME AS LOGINNAME,
	HOSTNAME AS HOST,
	GETDATE() AS [TIME]
FROM
    SYS.SYSPROCESSES
WHERE 
    DBID > 0 AND [SPID]	>50
GROUP BY 
    DBID, LOGINAME, HOSTNAME
ORDER BY 
	DB_NAME(DBID)

-- 2. MUESTRA NOMBRE DE BD, CANTIDAD DE CONEXIONES Y FECHA DE EJECUCION DE CONSULTA
SELECT 
    DB_NAME(DBID) AS DBNAME, 
    COUNT(DBID) AS NUMBEROFCONNECTIONS,
	GETDATE() AS [TIME]
FROM
    SYS.SYSPROCESSES
WHERE 
    DBID > 0 AND [SPID]	>50
GROUP BY 
    DBID
ORDER BY 
	DB_NAME(DBID)

-- 3. MUESTRA CANTIDAD DE CONEXIONES Y FECHA DE EJECUCION DE CONSULTA
SELECT 
	COUNT(DBID) AS TOTALCONNECTIONS, 
	GETDATE() AS [TIME] 
FROM 
	SYS.SYSPROCESSES 
WHERE 
	DBID > 0  AND [SPID] >50 