USE [DATABASE]
GO

ALTER DATABASE DATABASE_OLD MODIFY FILE (NAME =DATABASE_OLD, FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DATABASE_OLD.mdf')
GO

ALTER DATABASE  DATABASE_OLD MODIFY FILE (NAME = DATABASE_OLD_log, FILENAME ='C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DATABASE_OLD_log.ldf')
GO



ALTER DATABASE DATABASE_NEW MODIFY FILE (NAME =DATABASE_NEW, FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DATABASE_NEW.mdf')
GO

ALTER DATABASE  DATABASE_NEW MODIFY FILE (NAME = DATABASE_NEW_log, FILENAME ='C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DATABASE_NEW_log.ldf')
GO

