DECLARE @FREESPACEINGB VARCHAR(20)

SELECT DISTINCT DOVS.LOGICAL_VOLUME_NAME AS LOGICALNAME, DOVS.VOLUME_MOUNT_POINT AS DRIVE,
CONVERT(INT,DOVS.AVAILABLE_BYTES/1073741824.0) AS FREESPACEINGB, CONVERT(INT,DOVS.TOTAL_BYTES/1073741824.0) AS SPACEINGB,
CONVERT(INT, (DOVS.TOTAL_BYTES-DOVS.AVAILABLE_BYTES)/1073741824.0) AS USESPACEINGB,
(CONVERT(INT,DOVS.AVAILABLE_BYTES/1073741824.0)*100)/CONVERT(INT, (DOVS.TOTAL_BYTES)/1073741824.0) AS PLIBRE
FROM SYS.MASTER_FILES MF
CROSS APPLY SYS.DM_OS_VOLUME_STATS(MF.DATABASE_ID, MF.FILE_ID) DOVS
ORDER BY FREESPACEINGB ASC

SET @FREESPACEINGB = (SELECT DISTINCT (CONVERT(INT,DOVS.AVAILABLE_BYTES/1073741824.0)*100)/CONVERT(INT, (DOVS.TOTAL_BYTES)/1073741824.0) AS PLIBRE
FROM SYS.MASTER_FILES MF
CROSS APPLY SYS.DM_OS_VOLUME_STATS(MF.DATABASE_ID, MF.FILE_ID) DOVS WHERE DOVS.VOLUME_MOUNT_POINT LIKE '%C%')

SELECT @FREESPACEINGB
