USE master
GO

SELECT R.SESSION_ID, START_TIME, R.COMMAND,CONVERT(NUMERIC(6,2),R.PERCENT_COMPLETE)
AS [PERCENT COMPLETE],CONVERT(VARCHAR(20),DATEADD(MS,R.ESTIMATED_COMPLETION_TIME,GETDATE()),20) AS [ETA COMPLETION TIME],
CONVERT(NUMERIC(6,2),R.TOTAL_ELAPSED_TIME/1000.0/60.0) AS [ELAPSED MIN],
CONVERT(NUMERIC(6,2),R.ESTIMATED_COMPLETION_TIME/1000.0/60.0) AS [ETA MIN],
CONVERT(NUMERIC(6,2),R.ESTIMATED_COMPLETION_TIME/1000.0/60.0/60.0) AS [ETA HOURS],
CONVERT(VARCHAR(100),(SELECT SUBSTRING(TEXT,R.STATEMENT_START_OFFSET/2,
CASE WHEN R.STATEMENT_END_OFFSET = -1 THEN 1000 ELSE (R.STATEMENT_END_OFFSET-R.STATEMENT_START_OFFSET)/2 END)
FROM SYS.DM_EXEC_SQL_TEXT(SQL_HANDLE)))
FROM SYS.DM_EXEC_REQUESTS R WHERE COMMAND IN ('RESTORE DATABASE','BACKUP DATABASE')

-- RESULT:
--SESSION_ID	START_TIME				COMMAND				PERCENT COMPLETE	ETA COMPLETION TIME	ELAPSED MIN	ETA MIN	ETA HOURS	(No column name)
--62			2015-11-30 09:36:59.173	RESTORE DATABASE	72.99				2015-11-30 11:26:04	94.59		14.49	0.24		RESTORE DATABASE [SIIV] FROM  DISK = N'D:\BackupBD\SIIV\SIIV.bak' WITH  RESTRICTED_USER,  FILE = 1, 