DECLARE @IMAGER VARBINARY(MAX)
SELECT @IMAGER = BULKCOLUMN FROM OPENROWSET(BULK 'D:\FOTO-CORREGIDA.JPG', SINGLE_BLOB) AS FDOCUMENT

-- ACTUALIZA A BINARIO IMAGEN
UPDATE TABLA SET CAMPO=@IMAGER WHERE ID=ID+1
