GRANT SELECT ON ALL TABLES IN SCHEMA public TO user_dev; 
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO user_dev;

-- CREATE USER ONLY READ BD

CREATE USER USER_DEVELOPER

ALTER USER  USER_DEVELOPER WITH ENCRYPTED PASSWORD 'LDVG3DXP';

GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO USER_DEVELOPER;

--

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public 
TO user_name;
