GRANT SELECT ON ALL TABLES IN SCHEMA public TO user_dev; 
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO user_dev;

-- CREATE USER ONLY READ BD

CREATE USER USER_DEVELOPER
ALTER USER  USER_DEVELOPER WITH ENCRYPTED PASSWORD 'LDVG3DXP';
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO USER_DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user_name;

-- EJECUTAR EN CONSOLA PGADMIN3, SELECCIONANDO BD

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "USR_NFC";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "USR_NFC";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "USR_NFC";
