CREATE PROC [DBO]. [GMD_SPBUSCARTEXTO]
(
@TEXTOBUSCAR NVARCHAR (100)
)
AS
BEGIN



CREATE TABLE #RESULTADO (NOMBRECOLUMNA NVARCHAR(370 ), VALORCOLUMNA NVARCHAR( 3630))

SET NOCOUNT ON

DECLARE @NOMBRETABLA NVARCHAR( 256), @NOMBRECOLUMNA NVARCHAR (128), @TEXTOBUSCAR2 NVARCHAR(110 )
SET  @NOMBRETABLA = ''
SET @TEXTOBUSCAR2 = QUOTENAME('%' + @TEXTOBUSCAR + '%', '''')

WHILE @NOMBRETABLA IS NOT NULL
BEGIN
SET @NOMBRECOLUMNA = ''
SET @NOMBRETABLA =
(
SELECT MIN (QUOTENAME( TABLE_SCHEMA) + '.' + QUOTENAME(TABLE_NAME ))
FROM INFORMATION_SCHEMA .TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
AND QUOTENAME (TABLE_SCHEMA) + '.' + QUOTENAME( TABLE_NAME) > @NOMBRETABLA
AND OBJECTPROPERTY (
OBJECT_ID(
QUOTENAME(TABLE_SCHEMA ) + '.' + QUOTENAME (TABLE_NAME)
), 'ISMSSHIPPED'
       ) = 0
)

WHILE (@NOMBRETABLA IS NOT NULL) AND (@NOMBRECOLUMNA IS NOT NULL)
BEGIN
SET @NOMBRECOLUMNA =
(
SELECT MIN (QUOTENAME( COLUMN_NAME))
FROM INFORMATION_SCHEMA .COLUMNS
WHERE TABLE_SCHEMA = PARSENAME(@NOMBRETABLA , 2)
AND TABLE_NAME = PARSENAME(@NOMBRETABLA , 1)
AND DATA_TYPE IN ('CHAR', 'VARCHAR', 'NCHAR', 'NVARCHAR', 'UNIQUEIDENTIFIER')
AND QUOTENAME (COLUMN_NAME) > @NOMBRECOLUMNA
)

IF @NOMBRECOLUMNA IS NOT NULL
BEGIN
INSERT INTO #RESULTADO
EXEC
(
'SELECT ''' + @NOMBRETABLA + '.' + @NOMBRECOLUMNA + ''', LEFT(' + @NOMBRECOLUMNA + ', 3630)
FROM ' + @NOMBRETABLA + ' (NOLOCK) ' +
' WHERE ' + @NOMBRECOLUMNA + ' LIKE ' + @TEXTOBUSCAR2
)
END
END
END

SELECT NOMBRECOLUMNA , VALORCOLUMNA FROM #RESULTADO ORDER BY NOMBRECOLUMNA
END
