USE master
GO

ALTER DATABASE [TEST] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

-- Restore Backup Full

RESTORE DATABASE [TEST] FROM  DISK = N'D:\..\db.bak' WITH  RESTRICTED_USER,  FILE = 1,  
MOVE N'PRIMARY' TO N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TEST.mdf',  
MOVE N'MAIN_TABLES' TO N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\MAIN_TABLES_TEST.ndf',  
MOVE N'SECONDARY' TO N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SECONDARY_TEST.ndf',  
MOVE N'INDEXES' TO N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\INDEXES_TEST.ndf',  
MOVE N'log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\log_TEST.ldf',  
NORECOVERY,  NOUNLOAD,  REPLACE,  STATS = 5
GO

-- Restore Backup Differential
-- File = 1

RESTORE DATABASE [TEST] FROM  DISK = N'D:\..\db_D.bak' WITH  RESTRICTED_USER,  FILE = 1,  NOUNLOAD,  STATS = 5
GO

ALTER DATABASE [TEST] SET MULTI_USER
GO