-- CAMBIA COLLATION DE CAMPOS
-- EL COLLATION PERMITE ASOCIAR UN VALOR ÚNICO A CADA LETRA DEPENDIENDO DEL IDIOMA SELECCIONADO

USE DATABASE
GO

SELECT 'ALTER TABLE [' + SYS.OBJECTS.NAME + '] ALTER COLUMN ['
+ SYS.COLUMNS.NAME + '] ' + SYS.TYPES.NAME + 
    CASE SYS.TYPES.NAME
    WHEN 'TEXT' THEN ' '
    ELSE
    '(' + RTRIM(CASE SYS.COLUMNS.MAX_LENGTH
    WHEN -1 THEN 'MAX'
    ELSE CONVERT(CHAR,SYS.COLUMNS.MAX_LENGTH)
    END) + ') ' 
    END

    + ' ' + ' COLLATE MODERN_SPANISH_CI_AS ' + CASE SYS.COLUMNS.IS_NULLABLE WHEN 0 THEN 'NOT NULL' ELSE 'NULL' END
    FROM SYS.COLUMNS , SYS.OBJECTS , SYS.TYPES
    WHERE SYS.COLUMNS.OBJECT_ID = SYS.OBJECTS.OBJECT_ID
    AND SYS.OBJECTS.TYPE = 'U'
    AND SYS.TYPES.SYSTEM_TYPE_ID = SYS.COLUMNS.SYSTEM_TYPE_ID
    AND SYS.COLUMNS.COLLATION_NAME IS NOT NULL
    AND NOT ( SYS.OBJECTS.NAME LIKE 'SYS%' )
    AND NOT ( SYS.TYPES.NAME LIKE 'SYS%' )